using Wow.Core.IO.Text;
using Wow.Tools.ProtocolBuilder.Models;

namespace Wow.Tools.ProtocolBuilder.Renderers.Datacenter;

public sealed class DatacenterRenderer : IDatacenterRenderer
{
    public string Render(DbcClass dbcClass)
    {
        var builder = new IndentedStringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine()
            .AppendLine("using Wow.Core.IO.Dbc;")
            .AppendLine()
            .AppendLine("namespace Wow.Protocol.Datacenter;")
            .AppendLine()
            .AppendLine("public sealed class {0}", dbcClass.Name)
            .AppendLine('{')
            .Indent();

        foreach (var dbcProperty in dbcClass.Properties)
        {
            var type = dbcProperty.Type is "loc" ? "DbcCultures" : dbcProperty.Type;

            var line = $"public {(dbcProperty.ArraySize >= 0 ? string.Empty : "required ")}{type}{(dbcProperty.ArraySize >= 0 ? "[]" : string.Empty)} {dbcProperty.Name} {{ get; set; }}";
                
            if (dbcProperty.ArraySize >= 0)
                line += $" = new {type}[{dbcProperty.ArraySize}];";
                
            builder.AppendLine(line);

            if (dbcProperty != dbcClass.Properties.Last())
                builder.AppendLine();
        }

        return builder
            .UnIndent()
            .AppendLine('}')
            .ToString();
    }
}