using System.Diagnostics;

namespace Wow.Tools.ProtocolBuilder.Models;

[DebuggerDisplay("Name: {Name}, Type: {Type}, IsIndex: {IsIndex}, IsAutoGenerated: {IsAutoGenerated}, ArraySize: {ArraySize}")]
public sealed record DbcProperty(string Name, string Type, bool IsIndex, bool IsAutoGenerated, int ArraySize);